### ISSUE TITLE
Value

### ISSUE THREAD

**Issue by jrgs** [nachinsec/data_access_ian_2324#5]
https://github.com/nachinsec/data_access_ian_2324/blob/17c6f8d51c958a167b7dad23e59da38933b41013/unit2/Exercise4_4/src/Exercise4_4_3.java#L39

Esto no es buena idea, es mejor que estos métodos devuelvan el valor encontrado y que el programa principal se encargue de imprimirlo.

**Comment by nachinsec** [comment]
Lo he corregido y ahora se encarga el programa principal de imprimirlo
